---
title: "My website"
---

Hello, bienvenidos!

# Sección de contenido

Aquí va el texto y los elementos que quieres incluir en tu sitio web.




```{r}
#install.packages(c("shiny", "caret", "htmltools"))
library(caret)
library(tidyverse)

# Carga el modelo previamente ajustado y la funcion

modelo_logistico <- readRDS("modelo_logistico.rds")

prediccion_disponible <- readRDS("prediccion_disponible.rds")
```



```{r}
# Crear el formulario HTML
tags$form(
  action = "resultado.html",
  method = "get",
  tags$h2("Predicción de disponibilidad"),
  tags$label("Semana"),
  tags$input(type = "number", name = "week"),
  tags$label("Mes"),
  tags$input(type = "number", name = "month"),
  tags$label("Precio en dólares"),
  tags$input(type = "number", name = "price"),
  tags$label("Porcentaje reservado"),
  tags$input(type = "number", name = "percent_booked"),
  tags$label("Cluster"),
  tags$input(type = "number", name = "cluster"),
  tags$label("Alojamiento"),
  tags$input(type = "number", name = "accommodates"),
  tags$label("Tipo de estadia"),
  tags$select(
    name = "tipo_estadia",
    tags$option("corta"),
    tags$option("media 1"),
    tags$option("media 2")
  ),
  tags$label("Rating"),
  tags$input(type = "number", name = "rating"),
  tags$input(type = "submit", value = "Calcular predicción")
)
```



